### PR TITLE
Module renaming from MPD to MPDASH

### PR DESCRIPTION
**Pull request by Kobla**
I would like to make a package to Debian from your code.
But there is a problem with the actual module name.

Python packages in Debian should always be named after the highest-level
module available for import, which in this case appears to be mpd,
hence python[3]-mpd.

However, there is already a well-established "mpd" top-level Python
module, for the Music Player Daemon. (python-mpd, in Debian since 2008;
python-mpd and python-mpd2 on PyPI.

I changed module name to some non-colliding: mpd => mpdash.

Please, could you also change repository name? Perhaps python-mpdash-parser?

### CODE REVIEW

**Comment by onovy** [comment]
i suggest one of this:

1. repo python-mpd-parser AND module mpdparser
2. repo python-mpdash AND module mpdash // prefered :-)
3. repo python-mpdash-parser AND module mpdashparser

BTW: It's not only about collision in debian package name,  but in module name too. it's not possible to install mpd (music player daemon) and mpd (mpeg dash parser) together on same machine.

Thanks

**Comment by sangwonl** [comment]
yes, I agree with your suggestions. so, how about..

repo: python-mpdash (not only the clear category name but the big picture :) )
module: mpdash (it makes sense since it can have parser and other package)

by the way, how do you think which is more clear, mpdash or mpegdash?

**Comment by Kobla** [comment]
good question. mpegdash seems better to me.

So, I suggest:
repo: python-mpegdash
module: mpegdash

**Comment by sangwonl** [comment]
@Kobla 👍
yes, we shall go with `mpegdash`. I will change repository once the module renaming is done. :)

thanks

**Comment by Kobla** [comment]
Job done.
Now your turn, please :-)
Thanks

**Comment by sangwonl** [comment]
very thanks!

**Pull request merged**
